### ISSUE TITLE
A question about the  ingesting zcash data with blocksci

### ISSUE THREAD

**Issue by xingyushu** [graphsense/graphsense-blocksci#10]
zcash doesn't supprot disk parseing way,so I want to use the rpc method such as below command:
### hint:
`blocksci_parser <config file> generate-config <coin type> <data directory> [--max-block <max block>] [--disk <coin directory>] [--rpc <username> <password> [--address <address>] [--port <port>]]`

### test case:
`blocksci_parser /var/data/blocksci_data/zch.cfg generate-config zcash  /var/data/blocksci_data --max-block '-6' --rpc username password --address 172.17.0.1  --port 8632`

I wonder what the "--address" follow ? Is that the zcash docker container's IP or the host IP?

I did it like the  test case,but it doesn't work to meet the error:

```
dockeruser@8779af0b3405:~$ 16933GB of free disk space available.
OK: Open files limit of 1048576.

Locking data directory.

Error while interacting with RPC: std::exception
terminate called after throwing an instance of 'BitcoinException'
  what():  std::exception
```

**Comment by defconst** [comment]
Sorry for the late answer. This depends on the network setup. In our production setup we use a dedicated docker network (`graphsense-global-net `). From the blocksci container we just refer to the name of the zcash container (`zcash`), i.e. the blocksci config for ZEC looks as follows

```
{
    "chainConfig": {
        "coinName": "zcash",
        "dataDirectory": "/var/data/blocksci_data",
        "pubkeyPrefix": [
            28,
            184
        ],
        "scriptPrefix": [
            28,
            189
        ],
        "segwitActivationHeight": 2147483647,
        "segwitPrefix": "NONE"
    },
    "parser": {
        "maxBlockNum": -6,
        "rpc": {
            "address": "zcash",
            "password": "PASSWORD",
            "port": 8632,
            "username": "USERNAME"
        }
    },
    "version": 5
}
```
