### ISSUE TITLE
Deprecation of coinmarketcap api

### ISSUE THREAD

**Issue by dshatz** [graphsense/graphsense-blocksci#14]
This url no longer returns valid json: https://coinmarketcap.com/currencies/{currency}/historical-data/

As a result, `ingest-exchange-rates-*` services, which rely on `ingest_rates_coinmarketcap.py` no longer work. 
Their new API can not provide all the historical data from the beginning of times, on neither of the plans: https://coinmarketcap.com/api/pricing/

Coinmarketcap's frontend is communicating with this an api on different url, which is unprotected and does not have a limit set on historical data: 
https://web-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/historical?id=1&convert=USD&time_start=1291161600&time_end=1610323200

The downside of using this is that they could change input or output format, without anyone knowing.

Should I make a MR for the ingest script to use this api? Or are you aware of better options?

**Comment by dshatz** [comment]
This free API can provide historical prices, but one day at a time
http://api.coinlayer.com/api/2017-12-10?access_key=cdd456db44ddf44f9828a7d78378f47b&symbols=btc,ltc,bch,zec&target=eur

**Comment by defconst** [comment]
I also observed a few days ago that the scraper no longer works ... fixed in `develop`

**Comment by defconst** [comment]
> This free API can provide historical prices, but one day at a time
> http://api.coinlayer.com/api/2017-12-10?access_key=cdd456db44ddf44f9828a7d78378f47b&symbols=btc,ltc,bch,zec&target=eur

good to know :+1:

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @dshatz)
