### ISSUE TITLE
What happens now that BlockSci is legacy?

### ISSUE THREAD

**Issue by crantini** [graphsense/graphsense-blocksci#15]
As BlockSci has been demoted to legacy (https://github.com/citp/BlockSci/#blocksci) what is the roadmap for GraphSense with regards to this news?

**Comment by behas** [comment]
Build on sth like Blockchain ETL (https://github.com/blockchain-etl) and integrate transfer BlockSci-specific features (CoinJoins heuristics, address numbering) into the ingest / transformation

**Comment by mdragaschnig** [comment]
> Build on sth like Blockchain ETL (https://github.com/blockchain-etl) and integrate transfer BlockSci-specific features (CoinJoins heuristics, address numbering) into the ingest / transformation

See https://github.com/graphsense/graphsense-bitcoin-etl for further development.
