### ISSUE TITLE
Organize blocks in buckets

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-blocksci#18]
Improve block partitioning.

CREATE TABLE block (
    block_group int
    height int,
    block_hash blob,
    timestamp int,
    no_transactions int,
    PRIMARY KEY(block_group, height)
);

Allows efficient retrieval of latest block using a PER PARTITION LIMIT 1 query.

**Comment by defconst** [comment]
add WITH CLUSTERING ORDER BY (block_group DESC);

**Comment by mdragaschnig** [comment]
See also https://github.com/graphsense/graphsense-ethereum-transformation/issues/11
