### ISSUE TITLE
Change transaction partition key: index_group, index

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-blocksci#19]
CREATE TABLE transaction_by_group_id (
    tx_group int,
    tx_id bigint,
    tx_hash blob,
    height int,
    timestamp int,
    coinbase boolean,
    total_input bigint,
    total_output bigint,
    inputs list<FROZEN<tx_input_output>>,
    outputs list<FROZEN<tx_input_output>>,
    coinjoin boolean,
    PRIMARY KEY (tx_prefix, tx_hash)
);

**Comment by defconst** [comment]
solves #1

**Comment by mdragaschnig** [comment]
and add lookup table

CREATE TABLE transaction_by_tx_prefix (
    tx_prefix text,
    tx_hash blob,
    tx_ids list<bigint>,
    PRIMARY KEY (tx_prefix, tx_hash)
;
