### ISSUE TITLE
Add bucket_sizes and currencies to summary_statistics

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-blocksci#22]
CREATE TABLE summary_statistics (
    id text PRIMARY KEY,
    no_blocks int,
    no_txs bigint,
    timestamp int,
    blocks_bucket_size int,
    tx_bucket_size int, # if tables are written in raw keyspace
    tx_prefix_length int,
    addr_bucket_size int, # if tables are written in raw keyspace
    addr_prefix_length int # if tables are written in raw keyspace
);

OR write values to a separate configuration table.

**Comment by mdragaschnig** [comment]
Currencies are available in raw keyspace

CREATE TABLE exchange_rates (
    date text PRIMARY KEY,
    **fiat_values map<text, float>**
);

and transformed keyspace

CREATE TABLE configuration (
    keyspace_name text PRIMARY KEY,
    bucket_size int,
    bech_32_prefix text,
    coinjoin_filtering boolean,
    **fiat_currencies list<text>**
);

**Comment by mdragaschnig** [comment]
Leaving this open for now because  of addr_bucket_size and addr_prefix_length
